[2023-07-20T07:43:49.988+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingest.format_to_parquet_task scheduled__2023-07-19T00:00:00+00:00 [queued]>
[2023-07-20T07:43:50.006+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingest.format_to_parquet_task scheduled__2023-07-19T00:00:00+00:00 [queued]>
[2023-07-20T07:43:50.007+0000] {taskinstance.py:1308} INFO - Starting attempt 11 of 12
[2023-07-20T07:43:50.262+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2023-07-19 00:00:00+00:00
[2023-07-20T07:43:50.272+0000] {standard_task_runner.py:57} INFO - Started process 429 to run task
[2023-07-20T07:43:50.278+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingest', 'format_to_parquet_task', 'scheduled__2023-07-19T00:00:00+00:00', '--job-id', '796', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data.py', '--cfg-path', '/tmp/tmpqvjyjt8b']
[2023-07-20T07:43:50.283+0000] {standard_task_runner.py:85} INFO - Job 796: Subtask format_to_parquet_task
[2023-07-20T07:43:50.383+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingest.format_to_parquet_task scheduled__2023-07-19T00:00:00+00:00 [running]> on host 9224a5f59130
[2023-07-20T07:43:50.531+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingest' AIRFLOW_CTX_TASK_ID='format_to_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-19T00:00:00+00:00'
[2023-07-20T07:43:50.534+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data.py", line 33, in format_to_parquet
    with gzip.open(src_file,'rtb',encoding='UTF-8') as f:
  File "/usr/local/lib/python3.7/gzip.py", line 47, in open
    raise ValueError("Invalid mode: %r" % (mode,))
ValueError: Invalid mode: 'rtb'
[2023-07-20T07:43:50.551+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingest, task_id=format_to_parquet_task, execution_date=20230719T000000, start_date=20230720T074349, end_date=20230720T074350
[2023-07-20T07:43:50.576+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 796 for task format_to_parquet_task (Invalid mode: 'rtb'; 429)
[2023-07-20T07:43:50.615+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-20T07:43:50.665+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
